version: '3.8'

services:
  postgres:
    image: postgres:16.3
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    tmpfs:
      - /tmp
      - /run

    volumes:
      - ./local-postgres-init:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data:rw

volumes:
  rabbit:
    driver: local
  postgres:
    driver: local